[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

axum = { version = "0.4.2", features = ["multipart"] }

serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
  
tokio = {version = "1.0" , features = ["full"] }
tower = { version = "0.4", features = ["full"] }

tower-http = { version = "0.2", features = ["full"] }

mini-redis = "0.4"
int-enum = "*" 
enum-iterator = "*"

rand = "*"

bytes = "1"
futures = { version = "0.3", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.2"